<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsForPost($postId, $approved = true)
    {
        $queryBuilder = $this->createQueryBuilder('comment')
            ->andWhere('comment.post = :post_id')
            ->addOrderBy('comment.createdAt', 'DESC')
            ->setParameter('post_id', $postId);

        if (false === is_null($approved))
            $queryBuilder->andWhere('comment.approved = :approved')
                ->setParameter('approved', $approved);

        return $queryBuilder->getQuery()->getResult();
    }
}
